server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev

log:
  requests: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
          client:
            RestTemplate: DEBUG