version: '3.1'

services:
  mongo:
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P4ssw0rd
      MONGO_INITDB_DATABASE: recipe
    ports:
      - "27017:27017"