name: Build and Push Docker Image

on:
  workflow_run:
    workflows: [Build and Run Tests]
    types:
      - completed

jobs:
  build-and-push-docker-image:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build Image
        run: |-
          docker build "deployment/docker/backend" --build-arg VERSION=development-SNAPSHOT -t europe-west2-docker.pkg.dev/recipy-382818/recipe:$GITHUB_SHA

      - run: |
          gcloud auth configure-docker -q

      - name: Push Image
        run: |-
          docker push europe-west2-docker.pkg.dev/recipy-382818/recipe:$GITHUB_SHA