name: Build and Push Docker Image

on:
  workflow_run:
    workflows: [Build and Run Tests]
    types:
      - completed

jobs:
  build-and-push-docker-image:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Image
        run: |-
          docker build "deployment/docker/backend" --build-arg VERSION=development-SNAPSHOT -t eu.gcr.io/recipy-382818/recipe:$GITHUB_SHA

      - run: |
          gcloud auth configure-docker -q

      - name: Build
        run: |-
          docker push eu.gcr.io/recipy-382818/recipe:$GITHUB_SHA