# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Start Test Containers
        run: docker-compose -f "deployment/docker-compose.yaml" up -d --build

      - name: Build with Maven
        run: mvn clean install --batch-mode --update-snapshots

      - name: Report Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: '**/target/*-reports/**/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: Stop Containers
        if: always()
        run: docker-compose -f "deployment/docker-compose.yaml" down